// export const Anudanit = [
//   {
//     id: 1,
//     schoolName: "अनुदानित आश्रमशाळा भातसई",
//     place: "शहापूर",
//     district: "ठाणे",
//     principalName: "श्री .आनंद जर्नाधन वानखेडे / श्रीम.सारिका प्रकाश गायकवाड",
//     contact: "9623632335 / 7776943320",
//     president: "श्री अंभोरे नारायण दत्तात्रय",
//     presidentContact: "9763561981",
//     vicePresident: "श्रीम.लता बारीकराव खंडागळे",
//     vicePresidentContact: "8850454131",
//     email: "shrigadgemschool@gmail.com",
//   },
//   {
//     id: 2,
//     schoolName: "अनुदानित आश्रमशाळा गांडुळवाड",
//     place: "शहापूर",
//     district: "ठाणे",
//     principalName: "श्री.जी.के. चौधरी / श्री सुनिल मेणे",
//     contact: "8850756530 / 8805746099",
//     president: "श्री.रवींद्र देवराम लिहीतकर",
//     presidentContact: "9209094037",
//     vicePresident: "श्रीम.आशा झिजाबराव सिसोदे",
//     vicePresidentContact: "7378929635",
//     email: "ashramschoolgandulwad111@gmail.com",
//   },
//   {
//     id: 3,
//     schoolName: "अनुदानित आश्रमशाळा गाोठेघर",
//     place: "शहापूर",
//     district: "ठाणे",
//     principalName: "श्री.दिलीप किसन पाटील",
//     contact: "9405538640",
//     president: "श्री.जालिंदर आसराजी चव्हाण",
//     presidentContact: "9823568614",
//     vicePresident: "श्रीम.भाग्यश्री तुळशीराम पवार",
//     vicePresidentContact: "8999804954",
//     email: "hmpasm.gotheghar2024@gmail.com",
//   },
//   {
//     id: 4,
//     schoolName: "अनुदानित आश्रमशाळा चिंध्याचीवाडी",
//     place: "शहापूर",
//     district: "ठाणे",
//     principalName: "श्री.मनोज रमेश सिरसाळे / श्री चंदुलाल सावंत",
//     contact: "8669142114 / 9823493345",
//     president: "श्री. उमेश पांडुरंग जाधव",
//     presidentContact: "9764331296",
//     vicePresident: "श्रीम.माया मारुती पवार",
//     vicePresidentContact: "7875063812",
//     email: "crs2126@gmail.com",
//   },
//   {
//     id: 5,
//     schoolName: "अनुदानित आश्रमशाळा शिरोळे",
//     place: "भिवंडी",
//     district: "ठाणे",
//     principalName: "श्रीम. ए.एस. थोरात / श्रीम.सुजाता दोंदे",
//     contact: "9702269049 / 8928080289",
//     president: "श्री. महेशकुमार चंद्रकांत वाघ",
//     presidentContact: "9967695600",
//     vicePresident: "श्रीम.शैला बाजीराव पांडव",
//     vicePresidentContact: "9821815768",
//     email: "secondaryashramschool.shirole@gmail.com",
//   },
//   {
//     id: 6,
//     schoolName: "अनुदानित आश्रमशाळा भिवाळी",
//     place: "भिवंडी",
//     district: "ठाणे",
//     principalName: "श्री.अनिल पांडूरंग पदमणे / श्री.चंद्रकांत चौधरी",
//     contact: "9657136569 / 9421533445",
//     president: "श्री किरण भिमराव सुर्वे",
//     presidentContact: "7972618550",
//     vicePresident: "श्रीम.सविता रविंद्र पाटील",
//     vicePresidentContact: "8668387760",
//     email: "gadgeashramschool@gamil.com",
//   },
//   {
//     id: 7,
//     schoolName: "अनुदानित आश्रमशाळा रावत्याचापाडा",
//     place: "भिवंडी",
//     district: "ठाणे",
//     principalName: "श्रीम.ए.एस. रोकडे / श्री विकास ठाकरे",
//     contact: "9049012177 / 8999968328",
//     president: "श्री . संजयकुमार गुलाबराव ठाकरे",
//     presidentContact: "8668907749",
//     vicePresident: "श्रीम.शितल विठ्ठल पाटील",
//     vicePresidentContact: "9082273693",
//     email: "thakaresir1268@gmail.com",
//   },
//   {
//     id: 8,
//     schoolName: "अनुदानित आश्रमशाळा झापवाडी",
//     place: "मुरबाड",
//     district: "ठाणे",
//     principalName: "श्रीम.संजना संतोष घोरड / श्री महेश अहिरे",
//     contact: "9075774539 / 9604282128",
//     president: "श्री.शरद कृष्णा धलपे",
//     presidentContact: "9272777592",
//     vicePresident: "श्रीम.पुनम भिकाजी कोळी",
//     vicePresidentContact: "7020483873",
//     email: "zapwadischool@gmail.com",
//   },
//   {
//     id: 9,
//     schoolName: "अनुदानित आश्रमशाळा तळवली",
//     place: "मुरबाड",
//     district: "ठाणे",
//     principalName: "श्री.योगेंद्र वेखंडे / श्री के. एन.विशे",
//     contact: "9226975468 / 7798576585",
//     president: "श्री.अरविंद परसराम गायकर",
//     presidentContact: "9834417031",
//     vicePresident: "श्रीम.वंदना आप्पासाहेब सिने",
//     vicePresidentContact: "9653439916",
//     email: "talavali1999@gmail.com",
//   },
//   {
//     id: 10,
//     schoolName: "अनुदानित आश्रमशाळा वाल्हिवरे",
//     place: "मुरबाड",
//     district: "ठाणे",
//     principalName: "श्री.विकास राजाराम दळवी / श्री.दिनेश परसु लाटे",
//     contact: "8378941234 / 9209174184",
//     president: "श्री .संतोष वाळकू मोहपे",
//     presidentContact: "7822858880",
//     vicePresident: "श्रीम.संजया रमेश खाकर",
//     vicePresidentContact: "9579665105",
//     email: "anuashramvalhivare@gmail.com",
//   },
//   {
//     id: 11,
//     schoolName: "अनुदानित आश्रमशाळा लव्हाळी",
//     place: "अंबरनाथ",
//     district: "ठाणे",
//     principalName: "श्रीम. एस.आर.बुटेरे / श्री सी. बी.तारमळे",
//     contact: "8888646641 / 9604419507",
//     president: "श्री. मनोज सखाराम राठोड",
//     presidentContact: "9822833270",
//     vicePresident: "श्रीम.ज्योती सुनिल पोहाणे",
//     vicePresidentContact: "8830964749",
//     email: "guruvaryashikshan1996@gmail.com",
//   },
//   {
//     id: 12,
//     schoolName: "अनुदानित आश्रमशाळा काराव",
//     place: "अंबरनाथ",
//     district: "ठाणे",
//     principalName: "श्री. सुरेश दत्तु गोंधळी / श्रीम. आर. अे. पवार",
//     contact: "9284534399 / 8329420903",
//     president: "श्री.अजितसिंग जयसिंग गिरासे",
//     presidentContact: "9673257765",
//     vicePresident: "श्रीम.चंचला गजानन पाटील",
//     vicePresidentContact: "8850314869",
//     email: "pbjckarav2003@gmail.com",
//   },
//   {
//     id: 13,
//     schoolName: "अनुदानित आश्रमशाळा खडावली",
//     place: "कल्याण",
//     district: "ठाणे",
//     principalName: "श्री. दिपक डी. चव्हाण / श्री. शरद गोतारणे",
//     contact: "7709316164 / 7744028118",
//     president: "श्री.पंकज नाना पाटिल",
//     presidentContact: "9579294849",
//     vicePresident: "श्रीम.साक्षी समिर मोरे",
//     vicePresidentContact: "7558698541",
//     email: "chavhan.deepjyoti@gmail.com",
//   },
// ];
