// export const Hostel = [
//   {
//     id: 1,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह शहापूर",
//     Address: "श्री योगेश भोईर यांची इमारत गोठेघर शहापूर जि ठाणे",
//     place: "शहापूर",
//     District: "ठाणे",
//     WARDAN: "श्री. प्रणव निकम",
//     contact: "7517211777",
//     EmailId: "pranavnikam470@gmail.com",
//   },
//   {
//     id: 2,
//     Name: "आदिवासी मुलींचे शासकीय वसतिगृह शहापूर",
//     Address: "गंगा देवस्थान जवळ वाफे,तालुका शहापूर जिल्हा ठाणे",
//     place: "शहापुर",
//     District: "ठाणे",
//     WARDAN: "श्रीम.एस.आर.वाघमारे",
//     contact: "9226752023",
//     EmailId: "wardengirlshostel.shahapur1281@gmail.com",
//   },
//   {
//     id: 3,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह खर्डी ",
//     Address: "घर न १५३ जी प शाळेजवळ खर्डी .",
//     place: "शहापुर",
//     District: "ठाणे",
//     WARDAN: "श्री सी. आर. सोनवणे",
//     contact: "9049068696",
//     EmailId: "sonawanecr@gmail.com",
//   },
//   {
//     id: 4,
//     Name: "आदिवासी मुलींचे शासकीय वसतिगृह खर्डी ",
//     Address: "३३६,होलगीर यांची इमारत खर्डी",
//     place: "शहापुर",
//     District: "ठाणे",
//     WARDAN: "श्रीम.सिमा जोहरे",
//     contact: "9920885349",
//     EmailId: "wardengirlhostelkhardi@gmail.com",
//   },
//   {
//     id: 5,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह किन्हवली",
//     Address: "मू.पो. किन्हवली ता. शहापूर जि.ठाणे",
//     place: "शहापुर",
//     District: "ठाणे",
//     WARDAN: "श्री.अे.अे.कुलकर्णी",
//     contact: "9822080190",
//     EmailId: "kinhvaliboyshostel@gmail.com",
//   },
//   {
//     id: 6,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह मुरबाड",
//     Address: "हायड्रा कॉलनी, मुरबाड ,ता. मुरबाड , जि. ठाणे",
//     place: "मुरबाड",
//     District: "ठाणे",
//     WARDAN: "श्री. एस. ए, शिंगणे",
//     contact: "9595770235",
//     EmailId: "sachinshingne007@gmail.com",
//   },
//   {
//     id: 7,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह भिवंडी",
//     Address: "शिवाजी चौक, भिवंडी, ता. भिवंडी, जि. ठाणे",
//     place: "भिवंडी",
//     District: "ठाणे",
//     WARDAN: "श्री. प्रणव निकम",
//     contact: "7517211777",
//     EmailId: "pranavnikam470@gmail.com",
//   },
//   {
//     id: 8,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह कल्याण",
//     Address: "मंगेशी सिटी फेज १ कोलीवली कल्याण पश्चिम जि ठाणे",
//     place: "कल्याण",
//     District: "ठाणे",
//     WARDAN: "श्री.तुषार.जेठया.गावित",
//     contact: "7798402248",
//     EmailId: "gstbhostelkalyan11@gmail.com",
//   },
//   {
//     id: 9,
//     Name: "आदिवासी मुलींचे शासकीय वसतिगृह उल्हासनगर,",
//     Address: "नॅशनल शाळे समोर, ब्राह्मनपाडा जवळ, उल्हासनगर 4, जि -ठाणे",
//     place: "उल्हासनगर",
//     District: "ठाणे",
//     WARDAN: "श्रीम. के. सी. मोहिते",
//     contact: "8879303478",
//     EmailId: "kalyanimohite10@gmail.com",
//   },
//   {
//     id: 10,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह नवी मुंबई",
//     Address: "मु. सुकापुर ता. नविन पनवेल",
//     place: "पनवेल",
//     District: "रायगड",
//     WARDAN: "श्री. एस. ए, शिंगणे",
//     contact: "9595770235",
//     EmailId: "sachinshingne007@gmail.com",
//   },
//   {
//     id: 11,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह उल्हासनगर",
//     Address:
//       "शिव आराधना बिल्डिंग,1893समोर, तानाजी नगर कुर्ला कॅम्प, उल्हासनगर 5",
//     place: "उल्हासनगर",
//     District: "ठाणे",
//     WARDAN: "श्री. जी. आर. सोनवणे",
//     contact: "9223858584",
//     EmailId: "govtstbhunr@gmail.com",
//   },
//   {
//     id: 12,
//     Name: "आदिवासी मुलांचे शासकीय वसतिगृह मीरा भाईदर",
//     Address: "",
//     place: "ठाणे",
//     District: "ठाणे",
//     WARDAN: "श्री.अे.अे.कुलकर्णी",
//     contact: "9822080190",
//     EmailId: "mirabhayandarstboyshostel@gmail.com",
//   },
// ];
