export enum RouteNames {
  Home = "Home",
  DashBoard = "",
  About = "Introduction",
  AshramSchools = "Ashram Schools",
  InnovationChallenge = "Innovation Challenge",
  ScopeOfWork = "Scope of Work",
  GovernmentAshramSchools = "Government Ashram Schools",
  GovHostels = "Government Hostels",
  AidedAshram = "Government Aided Ashram",
  ProjectOfficerContact = "Project Officer Contact",
  VikasYoujna = "Vikas Youjna",
  Gallery = "Gallery",
  ContactUs = "Contact Us",
  LabharthiList = "Labharthi List",
  RightToInformation = "Right To Information",
  LokSevaHakka = "LokSeva Hakka",
  DownloadForm = "Download Form",
}
